## [CM 7] 
> by KEVAL PRAJAPATI (20908584)

## A) Iris Dataset

__Using a class of sklearn called GridSearchCV which allows one to compare different parameter of the classifiers by trying all the combination of those parameters and evaluates the model using cross-validation. Once it completes the evaluation it returns the best parameters for the model___



Comparing the best stats from previous questions                   
- i) __k__ = 10
- ii)__Accuracy__ = 95.23%
- iii) __F1-score__ = 95.52%
- iv) __AUC__ = 99.82 %
- v) __algorithm__ = auto
- vi) __metrics__ = minkowski
- vii) __p__ = 2
- viii) __weights__ = uniform


Best parameters returned by GridSearch
- i) __k__ = 10
- ii)__Accuracy__ = 95.80%
- iii) __F1-score__ = 95.52%
- iv) __AUC__ = 100 %
- v) __algorithm__ = ball_tree
- vi) __metrics__ = minkowski
- vii) __p__ = 2
- viii) __weights__ = uniform

Hence after the comparions one can conclude for given Iris dataset the KNN model is finely tuned with k(= No. of Neighbors)=10, Minkowski distance mertic of l2 form which is nothing but euclidean distance and uniform weight produces an accuracy of __95.23%__ , F1-score of __95.52%__ and auc score of __100%__.

In [91]:
# AUTHOR : KEVAL PRAJAPATI
# AIM : PARAMETER OPTIMIZATION

import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from matplotlib import pyplot as plt
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, auc, roc_curve, roc_auc_score,f1_score, classification_report,plot_roc_curve
from sklearn.model_selection import GridSearchCV

iris_df = pd.read_csv('D:\COLLEGE\Waterloo\TERM 1\ECE 657A\Assignment 1\dataset\iris_min_max.csv')


X = iris_df.iloc[:,:-1].values  # features
y = iris_df.iloc[:,4].values   # lables

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 98)

print("\n Size of training set : Features = ", X_train.shape, " Labels = ", y_train.shape)
print("\n Size of testing set : Features = ", X_test.shape, " Labels = ", y_test.shape)
print("\n Size of validation set : Features = ", X_val.shape, " Labels = ", y_val.shape)

# Training the model  on various parameters

k = [1,5,10,15,20,25,30,35]
metric_options = ['minkowski']
weight_options = ['uniform', 'distance']
p1 = [1,2]
algo = ['ball_tree', 'kd_tree', 'brute']
param_grid = dict(n_neighbors = k, weights = weight_options,algorithm  = algo, metric = metric_options, p = p1)
knn = KNeighborsClassifier()

grid = GridSearchCV(knn, param_grid, scoring = 'accuracy')
grid.fit(X_train_v, y_train_v)

# Best scores provided by the GridSearchCV
print("\n Best parameters:\n")
print ("\n Best accuracy score:",grid.best_score_)
print ("\n Best parameters: ",grid.best_params_)
print ("\n Best algorithm and neighbors: ",grid.best_estimator_)

# Training and testing the model on the parameters returned by GridSearchCV

knn_b = KNeighborsClassifier(10,weights = 'uniform',metric='minkowski',p=2, algorithm = 'ball_tree')
knn_b.fit(X_train_v,y_train_v)
y_pred_t = knn_b.predict(X_test)
accuracy_t= accuracy_score(y_test, y_pred_t)*100
print("\n Accuracy on test set: ",accuracy_t)
print("\n Classification report:\n")
print('\n Classification_report:')
print(classification_report(y_test, y_pred_t))
print('\n Confusion matrix:')
print(confusion_matrix(y_test, y_pred_t))
print("\n F1 score:",f1_score(y_test,y_pred_t, average='macro'))
y_prob = knn_b.predict_proba(X_test)
#fpr, tpr, thresh = roc_curve(y_test, y_prob)
auc = roc_auc_score(y_test, y_prob, multi_class='ovr')
print('AUC score:', auc)




 Size of training set : Features =  (82, 4)  Labels =  (82,)

 Size of testing set : Features =  (21, 4)  Labels =  (21,)

 Size of validation set : Features =  (11, 4)  Labels =  (11,)

 Best parameters:


 Best accuracy score: 0.9580952380952381

 Best parameters:  {'algorithm': 'ball_tree', 'metric': 'minkowski', 'n_neighbors': 10, 'p': 2, 'weights': 'uniform'}

 Best algorithm and neighbors:  KNeighborsClassifier(algorithm='ball_tree', n_neighbors=10)

 Accuracy on test set:  95.23809523809523

 Classification report:


 Classification_report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         4
Iris-versicolor       0.83      1.00      0.91         5
 Iris-virginica       1.00      0.92      0.96        12

       accuracy                           0.95        21
      macro avg       0.94      0.97      0.96        21
   weighted avg       0.96      0.95      0.95        21


 Confusion matrix:
[[ 4  0  0]
 [ 0  5  0]

## B) Heart Disease Dataset

Comparing the best stats from previous questions                   
- i) __k__ = 5
- ii)__Accuracy__ = 85.0%
- iii) __F1-score__ = 87.5%
- iv) __AUC__ = 91.92 %
- v) __algorithm__ = auto
- vi) __metrics__ = minkowski
- vii) __p__ = 2
- viii) __weights__ = uniform


Best parameters returned by GridSearch
- i) __k__ = 5
- ii)__Accuracy__ = 95.0%
- iii) __F1-score__ = 94.6%
- iv) __AUC__ = 96.3 %
- v) __algorithm__ = ball_tree
- vi) __metrics__ = minkowski
- vii) __p__ = 1
- viii) __weights__ = distane

Hence after the comparions one can conclude for given Heart Disease dataset the KNN model is finely tuned with k(= No. of Neighbors)=5, Minkowski distance mertic of l1 form which is nothing but manhattan distance and distance based weight produces an accuracy of __95.0%__ , F1-score of __94.6%__ and auc score of __96.3%__.

In [97]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from matplotlib import pyplot as plt
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, auc, roc_curve, roc_auc_score,f1_score, classification_report,plot_roc_curve


hd_df = pd.read_csv('D:\COLLEGE\Waterloo\TERM 1\ECE 657A\Assignment 1\dataset\heart_disease_missing_filled_min_max_final.csv')


# Splitting the data set into features and lables
X = hd_df.iloc[:,:-1].values  # features
y = hd_df.iloc[:,13].values   # lables


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 98)
#X_train_v, X_val, y_train_v, y_val = train_test_split(X_train, y_train, test_size=0.125, random_state=98)

print("\n Size of training set : Features = ", X_train.shape, " Labels = ", y_train.shape)
print("\n Size of testing set : Features = ", X_test.shape, " Labels = ", y_test.shape)
print("\n Size of validation set : Features = ", X_val.shape, " Labels = ", y_val.shape)

# Training the model using 5-fold cross validation method 

k = [1,5,10,15,20,25,30,35]
metric_options = ['minkowski']
weight_options = ['uniform', 'distance']
p1 = [1,2]
algo = ['auto','ball_tree', 'kd_tree', 'brute']
param_grid = dict(n_neighbors = k, weights = weight_options,algorithm  = algo, metric = metric_options, p = p1)
knn = KNeighborsClassifier()

grid = GridSearchCV(knn, param_grid, scoring = 'accuracy')
grid.fit(X_train, y_train)

print("\n Best parameters:\n")
print ("\n Best accuracy score:",grid.best_score_)
print ("\n Best parameters: ",grid.best_params_)
print ("\n Best algorithm and neighbors: ",grid.best_estimator_)

# Training and testing the model on the parameters returned by GridSearchCV
knn_b = KNeighborsClassifier(10,weights = 'distance',metric='minkowski',p=1, algorithm = 'ball_tree')
knn_b.fit(X_train,y_train)
y_pred_t = knn_b.predict(X_test)
accuracy_t= accuracy_score(y_test, y_pred_t)*100
print("\n Accuracy on test set: ",accuracy_t)
print("\n Classification report:\n")

print(classification_report(y_test, y_pred_t))
print('\n Confusion matrix:')
print(confusion_matrix(y_test, y_pred_t))
print("\n F1 score:", f1_score(y_test,y_pred_t, average='macro'))
y_prob = knn_b.predict_proba(X_test)[::,1]
fpr, tpr, thresh = roc_curve(y_test, y_prob)
auc = roc_auc_score(y_test, y_prob)
print('AUC score:', auc)



 Size of training set : Features =  (156, 13)  Labels =  (156,)

 Size of testing set : Features =  (40, 13)  Labels =  (40,)

 Size of validation set : Features =  (11, 4)  Labels =  (11,)

 Best parameters:


 Best accuracy score: 0.8584677419354838

 Best parameters:  {'algorithm': 'auto', 'metric': 'minkowski', 'n_neighbors': 10, 'p': 1, 'weights': 'distance'}

 Best algorithm and neighbors:  KNeighborsClassifier(n_neighbors=10, p=1, weights='distance')

 Accuracy on test set:  95.0

 Classification report:

              precision    recall  f1-score   support

           0       1.00      0.88      0.93        16
           1       0.92      1.00      0.96        24

    accuracy                           0.95        40
   macro avg       0.96      0.94      0.95        40
weighted avg       0.95      0.95      0.95        40


 Confusion matrix:
[[14  2]
 [ 0 24]]

 F1 score: 0.9466666666666668
AUC score: 0.9635416666666666


__References__
- https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
- https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html
- https://towardsdatascience.com/ways-to-detect-and-remove-the-outliers-404d16608dba

